name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run ShellCheck on linkChecker.sh
      run: |
        shellcheck -s bash ./linkChecker.sh
      continue-on-error: false

    - name: Run ShellCheck on Bats test file
      run: |
        shellcheck -s bash ./tests/linkchecker.bats
      continue-on-error: false

    - name: Run ShellCheck on test_helper.bash
      run: |
        shellcheck -s bash ./tests/test_helper.bash
      continue-on-error: false

  bats-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Bats
      run: |
        sudo apt-get update
        sudo apt-get install -y bats

    - name: Run Bats Tests
      run: bats tests/
      continue-on-error: false
