name: ShellCheck

on:
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run ShellCheck
      run: |
        output=$(shellcheck -s bash ./linkChecker.sh)
        echo "$output"
        if [ -n "$output" ]; then
          echo "::error::ShellCheck found issues in the script"
          exit 1  # Hata kodu döndür
        fi

    - name: Fail if errors found
      run: exit 1
      if: ${{ failure() }}