name: ShellCheck

on:
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run ShellCheck
      run: shellcheck -s bash ./linkChecker.sh || true

    - name: Fail if errors found
      run: exit 1
      if: ${{ failure() }}